### ISSUE TITLE
mvp-cockpit: updating port forwards is not working

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#115]
When creating a VM using following blueprint:
```
node.ovc__vm4docker:
  description: 'vm for testing app_docker cl'
  bootdisk.size: 10
  memory: 2
  os.image: 'Ubuntu 16.04 x64'
  ports:
    - '7122:22'
```

Updating the port forwards should be possible with following blueprint:
```
node.ovc__vm4docker:
  ports:
    - '7122:22'
    - '22:2210'
actions:
  - action: install
```

Doesn't work
