### ISSUE TITLE
uservdc list is ignored

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#153]
Blueprint:
```
g8client__artiliumadmin:
  url: 'uk-g8-1.demo.greenitglobe.com'
  login: '...'
  password: '...'
  account: 'Artilium Account'

uservdc__ivancoene:
  g8client: 'artiliumadmin'
  email: 'ivan.coene@artilium.com'
  provider: 'itsyouonline'

vdc__ivanvdc3:
  g8client: 'artiliumadmin'
  location: 'uk-g8-1'
  account: 'Artilium Account'
  uservdc:
    - 'ivancoene'

actions:
  - action: install
```

Result:
- ivancoene gets created
- But is not granted user access:
https://uk-g8-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=81#users-access

**Comment by yveskerwyn** [comment]
Also this blueprint didn't work:

```
g8client__cl:
  url: uk-g8-1.demo.greenitglobe.com
  login: ...
  password: ...
  account: Account of Yves

uservdc__yves@itsyouonline:
  g8client: cl

vdc__simplevdc:
  g8client: cl
  account: Account of Yves
  location: uk-g8-1
  uservdc:
  - yves@itsyouonline

actions:
  - action: install
```

In this case "yves@itsyouonline" is an existing user

Expected result is that this user gets granted user access to simplevdc:
https://uk-g8-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=84#users-access

**Comment by yveskerwyn** [comment]
Here's another example, for a new user:

```
g8client__cl:
  url: uk-g8-1.demo.greenitglobe.com
  login: cockpit
  password: cockpit12345
  account: Account of Yves

uservdc__bill:
  g8client: cl
  email: 'billl@gat.es'
  provider: 'itsyouonline'

vdc__simplevdc12:
  g8client: cl
  account: Account of Yves
  location: uk-g8-1
  uservdc:
  - bill

actions:
  - action: install
````

Result:

- bill got created successfully:
https://uk-g8-1.demo.greenitglobe.com/system/user?id=bill@itsyouonline

BUT

- bill was not granted access to the new vdc:
https://uk-g8-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=103
