### ISSUE TITLE
VM has been created with the wrong size.

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_jumpscale8#164]
I ran the below blueprint to create vm with sizeID:4, and i got one with sizeid=2 (1024M)
## Blueprint
```
sshkey__john:
    key.path: '/root/.ssh/id_rsa'

g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'john'
    password: 'gig12345'
    account: 'johnacc'

vdc__johncs3:
    g8client: 'main'
    description: 'desc'
    location: 'du-conv-2'

node.ovc__builder:
    os.image: 'Ubuntu 16.04 x64'
    bootdisk.size: 10
    sizeID: 4
    vdc: 'johncs3'
    sshkey: 'main'
```
![exe](https://cloud.githubusercontent.com/assets/15011431/22467930/2d6fe6b4-e7cf-11e6-91cc-0c2fd4ec1a12.png)
![bug2](https://cloud.githubusercontent.com/assets/15011431/22467933/3023d56e-e7cf-11e6-9efa-a2530017637c.png)

## Version
ays8: 8.1.1
js8: 8.1.1
