### ISSUE TITLE
User access is not set when create new VDC

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#183]
See below blueprint.

**Repository**: 
```
ssh cloudscalers@10.101.101.135 -p7122 (password: 4GgwKh3iB)
cd /optvar/cockpit_repos/test2
```

**Expected result** is that the user `jdelrue` gets granted user access to the VDC, which is not the case; see result in the screenshot. 

**Blueprint**:

```
g8client__cl:
  url: 'be-scale-1.demo.greenitglobe.com'
  login: 'cockpit_api_user'
  password: 'cockpit12345'
  account: 'Account of Yves'

uservdc__jdelrue:
  g8client: 'cl'
  email: 'delrue.jonas@gmail.com'
  provider: 'itsyouonline'

vdc__testvdc2:
  g8client: 'cl'
  location: 'be-scale-1'
  maxMemoryCapacity: 128
  maxDiskCapacity: 10
  maxCPUCapacity: 5
  maxNumPublicIP: 5
  account: 'Account of Yves'
  uservdc:
    - 'jdelrue'
```

**Result**: 

https://be-scale-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=198

![screen shot 2017-02-22 at 11 44 48](https://cloud.githubusercontent.com/assets/13795109/23208192/56ff6956-f8f4-11e6-8def-887980fbe318.png)

**Comment by yveskerwyn** [comment]
After having restarted a run, to user access got corrected.
We haven't been able to reproduce afterwards, so we close for now.

**Comment by yveskerwyn** [comment]
I've been able to reproduce, see: `/optvar/cockpit_repos/37a1Evolutyves/blueprints``

It seems you get this problem if the `uservdc` and `vdc` definitions are in separate blueprints.

Should AYS be able to cope with this?

**Comment by yveskerwyn** [comment]
Explicitly numbering the blueprints doesn't help...

See `/optvar/cockpit_repos/test6`:

```
root@vm-352:/optvar/cockpit_repos/test6# ls blueprints/ -1
1_client.yaml
2_uservdc.yaml
3_vdc.yaml
```

See result: https://be-scale-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=217

![screen shot 2017-02-23 at 10 34 33](https://cloud.githubusercontent.com/assets/13795109/23253133/adf7ac36-f9b3-11e6-831a-f2672df424b7.png)

**Comment by yveskerwyn** [comment]
And using one single blueprint doesn't solve the problem neither...

See `/optvar/cockpit_repos/test7`

Blueprint:

```
g8client__artiliumadmin:
  url: 'be-scale-1.demo.greenitglobe.com'
  login: 'cockpit_api_user'
  password: 'cockpit12345'
  account: 'Account of Artilium'

uservdc__yves:
  g8client: 'artiliumadmin'
  email: 'yves_kerwyn@hotmail.com'
  provider: 'itsyouonline'

vdc__test7:
  g8client: 'artiliumadmin'
  location: 'be-scale-1'
  maxMemoryCapacity: 64
  maxDiskCapacity: 1024
  maxCPUCapacity: 10
  maxNumPublicIP: 1
  account: 'Account of Artilium'
  uservdc:
    - 'yves'

actions:
  - action: install
```

Result: https://be-scale-1.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=219

![screen shot 2017-02-23 at 10 43 34](https://cloud.githubusercontent.com/assets/13795109/23253473/f0b057e8-f9b4-11e6-93f0-3065f4a879ac.png)
