### ISSUE TITLE
node.docker actor's doc is missing consume of app_docker

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#193]
**Description**
node.docker actor is consuming app_docker service and this isn't mention in the doc example. May be it should be consumed by default.
https://github.com/Jumpscale/ays_jumpscale8/tree/8.1.1/templates/nodes/node.docker

Please review this part too as the blueprint doesn't need it anymore.
```yaml
os.ssh.ubuntu__docker_ovh4:
  sshkey: 'ovh_install'
  node: 'ubuntutest'
```

Branch: AYS 8.1.1
