### ISSUE TITLE
Internal server error on perfect valid blueprint for deploying ownCloud

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#207]
See: http://lci.ma.gig.tech/ays81/repo?repo=dalius3&repopath=/optvar/cockpit_repos/dalius3

Following blueprint is used (masked login and password):

```
g8client__ma:
  url: 'ma-g8-1.demo.greenitglobe.com'
  login: '****'
  password: '*****'
  account: 'Account of Dalius'

vdc__daliusvdc1:
  g8client: 'ma'
  location: 'ma-g8-1'

blueowncloud__daliuscloud3:
  vdc: 'daliusvdc3'
  datadisks:
    - 1000
    - 1000
  hostprefix: 'daliuscloud3'

actions:
  - action: install
```

When copying this blueprint in the quick entry field and clicking Apply, I get the below error, even while the same blueprint works just fine when using it at the CLI:

<img width="1108" alt="screen shot 2017-03-22 at 21 57 42" src="https://cloud.githubusercontent.com/assets/13795109/24213044/a9bf8646-0f4a-11e7-9cc5-a8504095ce0e.png">
