### ISSUE TITLE
False error when create an account and assign it to another user

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#211]
**Description**
Creating a new account and assigning it to another account will produce a false error (It was producing an error while the account was created in the env.)

**Blueprint**
```yaml
g8client__islam:
  url: 'du-conv-2.demo.greenitglobe.com'
  login: 'driver'
  password: 'driver_123'

account__321456789:
  description: 'pmd312'
  g8client: 'islam'
  accountusers:
   - 'installer'

actions:
   - action: 'install'

```

**Actual Result**
![screenshot from 2017-03-27 11-30-21](https://cloud.githubusercontent.com/assets/17981089/24349992/5028a7fa-12e9-11e7-89b8-a8394999caec.png)

![screenshot from 2017-03-27 11-26-26](https://cloud.githubusercontent.com/assets/17981089/24349962/3c906d68-12e9-11e7-8cfe-a901051610ba.png)

**Expected result**
Assigning an account to another user should be succeeded without errors.

**Version**
8.1.1
