### ISSUE TITLE
autosnapshotting service isn't working

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#215]
**Test case**
```bash
python3 cockpit_testing/Framework/Driver/Driver.py -b auto_snapshoting
```

**Test Result**
```bash
 * Driver is running ..... 
 * Test case : auto_snapshoting.yaml
 * CREATED : 175bf7b7e3 repo
 * CREATED : 8329f7b733 blueprint in 175bf7b7e3 repo
 * EXECUTED : 8329f7b733 blueprint in 175bf7b7e3 repo
 * RAN : 175bf7b7e3 repo
 * The Running state is ok 
 * RESULT: FAILED : ["FAILED : test_auto_snapshoting {'status_code': 200, 'machineId': 2525, 'url': 'https://du-conv-2.demo.greenitglobe.com/restmachine/cloudapi/machines/listSnapshots', 'content': b'[]'}"]
 * Generate XML results

```

**Blepuprint**
```yaml
g8client__islam:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'driver'
    password: 'driver_123'

vdc__0793c9c75b:
    description: 'e89c838dc7'
    g8client: 'islam'
    account: '1c03daea50'
    location: 'du-conv-2'
    uservdc:
        - 'driver'

node.ovc__5584378f7c:
    os.image: 'Ubuntu 16.04 x64'
    bootdisk.size: 10
    sizeID: 2
    vdc: 0793c9c75b

autosnapshotting__ab9a466288:
  vdc: 0793c9c75b
  snapshotInterval: '2m'
  retention: '5m'
  cleanupInterval : '1m'

# 'QA SERVICE' (THE TEMPLATE SHOULD HAS THIS LINE)
test_auto_snapshoting__353b190932:
   g8client: 'islam'
   autosnapshotting: ab9a466288
   node: 5584378f7c

actions:
   - action: 'install'
   - action: 'test_auto_snapshoting'
     actor: test_auto_snapshoting
```

**Actual result**
There is no snapshots and there is no snapshot API requests 
![screenshot from 2017-03-27 18-07-29](https://cloud.githubusercontent.com/assets/17981089/24366145/e258b5ca-1320-11e7-8bb5-a1136d8b10f2.png)

**Version**
8.1.1

**Comment by xmonader** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/64129/24500538/0d5e36a6-1546-11e7-91e8-1e722e2e3c8c.png)

```
g8client__env1:
  url: 'be-g8-4.demo.greenitglobe.com'
  login: '***'
  password: '***'
  account: '***'

vdc__testsnap5:
  description: 'testsnap'
  g8client: env1
  location: 'be-g8-4'
  uservdc:
    - 'thabet'

node.ovc__myn1:
  os.image: 'Ubuntu 16.04 x64'
  bootdisk.size: 10
  sizeID: 2
  vdc: testsnap5

autosnapshotting__d5aef9bbef:
  vdc: testsnap5
  snapshotInterval: '2m'
  cleanupInterval: '4m'
  retention: '10d'

```
