### ISSUE TITLE
No support yet to add users to existing an VDC (instance)

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#62]
Currently there is no implementation yet for executing (fragments of) VDC blueprints such as:
vdc__test-vdc-10:  
  ovc_user:
    - 'new user'

When executing such a blueprint nothing happens...

We haven't decided yet how to enable adding users to existing VDC...

**Comment by khaledkbadr** [comment]
In ays81 branch you can execute the below print.
```
g8client__main_g8:
    url: 'gig.demo.greenitglobe.com'
    login: 'khaled'
    password: '********'
    account: 'khaled'

vdc__test-vdc-10:
    location: 'be-scale-2'
    g8client: 'main_g8'

vdc_user__vdcusr:
    vdc: 'test-vdc-10'
    userid: 'admin'
```
