### ISSUE TITLE
mvp-cockpit: refactor vdc actor templates to implement all committed features.

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#76]
Error when creating a new VDC using following blueprint:

```
vdc__vdc4yves02:
  g8client: artiliumadmin
  account: Artilium Account
  location: be-scale-2
```
See the run details page for the traceback in the log (screenshot) of following run:
https://artilium.aydo2.com/ays81/job?jobid=e4f94a8f4586c10e3f70648a952ab534&runid=2e6f40e0702dbc439cb7e4bd470ec8ae&reponame=yves02&ayspath=/optvar/cockpit_repos/yves02

![screen shot 2016-11-25 at 11 07 44](https://cloud.githubusercontent.com/assets/13795109/20621607/708dd258-b2ff-11e6-80ca-7b85abe11b0e.png)
