### ISSUE TITLE
example blueprint: vm on openvcloud with docker

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/ays_jumpscale8#80]
- in this repo, create /blueprintexamples
- show 3 blueprints
   - how to put credentials of OVC
   - how to create a VM for ubuntu
   - how to install a chosen docker from the docker repo outside, expose port to outside world

**Comment by rkhamis** [comment]
@despiegk, why don't we create a demo repo in https://github.com/Jumpscale/jumpscale_ays8_testenv? I'd like to keep this repo blueprint-free. It should only contain actor templates.

**Comment by rkhamis** [comment]
blueprints:

- ovc_auth.yaml

```
g8client__env:
    url: '{env-url}'
    login: '{login}'
    password: '{password}'
```

- vm.yaml
```
# create/specify which virtual data center to use
vdc__{vdc_name}:
    description: 'vdc for demo'
    g8client: 'env'
    account: '{account_to_use}'
    location: '{location}'

# create an sshkey to later access your vm
sshkey__main:

# create the vm.
# expose ports 22. Map it to 2210.
# authorize sshkey created on the vm
node.ovc__{vm_name}:
    bootdisk.size: 50
    memory: 2
    os.image: 'Ubuntu 16.04 x64'
    ports:
        - '22:2210'
    sshkey: 'main'
```

- docker.yaml
```
# create the docker, specifying what image to use
node.docker__{docker_name}:
        image: '{image_name}',
        hostname: {docker_name},
        os: {vm_name},
        ports: 
          -   '2210:22'

# an os layer to get access to the docker
os.ssh.ubuntu__main:
     sshkey: main
     node: {docker_name}
```
