### ISSUE TITLE
Blocking Issue: 500 status code response when create a vdc without specs

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#85]
steps:
Run the following blueprint
```
g8client__islam:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'gig'
    password: *****

# create the vdc that will contain the vm of the CockpitTesting
vdc__d6bd7e8933:
    description: 'b84e68881f'
    g8client: 'islam'
    account: 'Automatedqa'
    location: 'du-conv-2'
    uservdc:
        - 'gig'

# 'QA SERVICE' (THE TEMPLATE SHOULD HAS THIS LINE)
create_cloudspace_test__a793373855:
   vdc: d6bd7e8933

actions:
   - action: 'install'
   - action: 'create_cloudspace_test'
     actor: create_cloudspace_test
```

**Actual Result**
ERROR : response status code 500 {
  "error": "Error during execution of the blueprint:\n src/capnp/dynamic.c++:1609: failed: expected value >= 0 && T(value) == value; Value out-of-range for requested type.; value = -1\nstack: 0x7f0030e7fb09 0x7f0030e8373d 0x7f0030e5a556 0x7f0030e55b47 0x7f0030e56249 0x7f0030e56bc4 0x7f0030e5834b 0x7f0030d50521 0x7f0030d53af5 0x7f0030cd0e48 0x7f0030ccbd74 0x7f0030ce639b 0x7f0030ce66d2 0x4e1757 0x5bcf47 0x51cc77"
}
