### ISSUE TITLE
mvp-cockpit: autosnapshotting doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#88]
See below blueprint that executed + installed successfully:
```
autosnapshotting__snapshotting4yves02:
  vdc: vdc4yves02
  snapshotInterval: '2h'
  cleanupInterval: '1d'
  retention: '5d'

actions:
  - action: install
    actor: autosnapshotting
    service: snapshotting4yves02 
```

Immediately after installation no job was created:

<img width="1162" alt="screen shot 2016-12-05 at 14 45 31" src="https://cloud.githubusercontent.com/assets/13795109/20887104/8c53f678-baf9-11e6-8ac2-c567f684e8e2.png">

Question: how can I verify that the first snapshot will actually happen?

Two hours later, still no snapshot was taken, so something is not working
